name: Sync with HuggingFace Spaces

on:
  push:
    branches: ['main']

env:
  HF_USERNAME: lucasvmigotto
  HF_SPACE_NAME: mba-dsa

jobs:
  sync-to-hf-spaces:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ env.HF_USERNAME }}
          HF_SPACE_NAME: ${{ env.HF_SPACE_NAME }}
        run: git push -f https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME main
